In [37]:
from chord import Chord
%matplotlib inline

import random
import nltk, re, pprint
from nltk import word_tokenize
from nltk.corpus import stopwords
import pandas as pd
import matplotlib.pyplot as plt
import copy
import numpy as np
import seaborn as sns
import itertools
import pickle
import math
import networkx as nx
import community
import pickle 
from collections import Counter
from wordcloud import WordCloud, ImageColorGenerator
from operator import itemgetter
from fa2 import ForceAtlas2
sns.set()
%matplotlib inline

# Sankey circle chart
First we need to gather the data of which characters interact with eachother, and gather into a dictionary.

In [103]:
with open('char_interactions.pickle', 'rb') as handle:
    char_interactions_dict = pickle.load(handle)

Since the Chord used a matrix as input for the graph data, it is necessary to convert this information into a matrix.

In [104]:
char_interactions_dict[('Albus Dumbledore', 'Mcgonagall')]

5

As there are so many characters with very few interactions, the dictionary will be filterd to only include those character combinations that have at least 4 scenes together.

In [115]:
# Filter dictionary where value greater than 2
char_interactions_dict = { key:value for (key,value) in char_interactions_dict.items() if value > 3}

First we need to extract a list of all the characters in the dictionary.

In [116]:
all_characters = list(set([item for t in char_interactions_dict.keys() for item in t]))
print("Total number of characters: ", len(all_characters))

Total number of characters:  64


And from the dictionary a matrix can be computed and converted into a list of lists, since that is the format of the data needed for the diagram.

In [117]:
# Genearte empty matrix
chord_data = np.zeros((len(all_characters), len(all_characters)), dtype=int)

# Loop over dict and populate matrix (which is symmetric)
for key in char_interactions_dict:
    i = all_characters.index(key[0])
    j = all_characters.index(key[1])
    chord_data[i, j] = char_interactions_dict[key]
    chord_data[j, i] = char_interactions_dict[key]

# Convert matrix to list of lists.
chord_data = chord_data.tolist()

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [122]:
# Plot and save to html
Chord(chord_data, all_characters, width=800, margin=80, font_size_large="14px", padding = 0.02, credit=True).to_html()